# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: test deploy
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  deploy-test:
    name: deploy
    timeout-minutes: 11
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - "debian13"
          - "ubuntu24"
          - "ubuntu26"
        platform:
          - docker
          - podman
          - nspawn
        ansible_ver:
          - "11"
    steps:
      - uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          fetch-depth: 0
          submodules: true
          persist-credentials: false
      - name: test ansible deploy
        env:
          DISTRO: ${{ matrix.distro }}
          PLATFORM: ${{ matrix.platform }}
          ANSIBLE_VER: ${{ matrix.ansible_ver }}
        run: "bin/deploy-test.sh"
  linters:
    name: linters
    timeout-minutes: 11
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          fetch-depth: 0
          submodules: true
          persist-credentials: false
      - name: lint the repo
        env:
          BRA: master
        run: |
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/linters-ubuntu-22_04/check-dir.sh | bash
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/ansible-ubuntu/check-dir.sh | bash
  MegaLinter:
    name: MegaLinter
    timeout-minutes: 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          fetch-depth: 0
          submodules: true
          persist-credentials: false
      - name: MegaLinter
        uses: oxsecurity/megalinter@v9 # zizmor: ignore[unpinned-uses]
        env:
          VALIDATE_ALL_CODEBASE: true
  all-green:
    name: all green
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - deploy-test
      - linters
      - MegaLinter
    if: always()
    permissions:
      checks: read
    steps:
      - name: waiting for checks success
        uses: poseidon/wait-for-status-checks@v0.6.0 # zizmor: ignore[unpinned-uses]
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: all green, foobar
          timeout: 111s
